"""empty message

Revision ID: f3d87cf788b3
Revises: 69eaec894116
Create Date: 2021-10-24 21:34:59.833494

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3d87cf788b3'
down_revision = '69eaec894116'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('category', 'created_at')
    # ### end Alembic commands ###
